
# MODIFICAR ESTE ARCHIVO PARA AÃ‘ADIR NUEVAS MICRO-SERVICIOS

services:

  nats-server:
    container_name: nats_server_nc
    image: nats:latest
    ports:
      - "8222:8222"

# =================================================
# Client Gateway
# =================================================

  client-gateway:
    container_name: client_gateway_nc
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3003
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222

# =================================================
# Products Microservice
# =================================================

  products-ms:
    container_name: products_ms_nc
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

# =================================================
#  Auth Microservice
# =================================================
  
  auth-ms:
    container_name: auth_ms_nc
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}


# =================================================
#  Orders Microservice
# =================================================

  order-ms:
    container_name: order_ms_nc
    depends_on:
      orders-db:
        condition: service_healthy
    build: ./order-ms
    volumes:
      - ./order-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:654321@orders-db:5432/orderdbnc?schema=public


# =================================================
# Orders Database
# =================================================

  orders-db:
    container_name: order_db_nc
    image: postgres:16.2
    restart: always
    volumes:
      - ./order-ms/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=654321
      - POSTGRES_DB=orderdbnc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

# =================================================
# Payments Microservice
# =================================================

  payments-ms:
    container_name: payments_ms_nc
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - MERCADOPAGO_PUBLIC_KEY=${MERCADOPAGO_PUBLIC_KEY}
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
    # - MP_SUCCESS_URL=${STRIPE_SUCCESS_URL}
    # - MP_CANCEL_URL=${STRIPE_CANCEL_URL}